title: 记录点滴
description: > # this means to ignore newlines until "baseurl:"
    This is my first blog!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Tong Shujian # add your name
author-img: tong-shujian.jpg # add your photo
about-author: 想要改变世界，却只能随波逐流。 # add description
twitter: tong467 # add your Twitter handle
facebook: # add your Facebook handle
github: tong467 # add your Github handle
linkedin: tong467 # add your Linkedin handle
email: tong467@126.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
